"""FastAPI entrypoint wiring the ChatKit server and REST endpoints."""

from __future__ import annotations

from chatkit.server import StreamingResult
from fastapi import Depends, FastAPI, HTTPException, Request, status
from fastapi.responses import FileResponse, Response, StreamingResponse
from starlette.responses import JSONResponse

from .chat import (
    REPORTS_DIR,
    TraccarAssistantServer,
    create_chatkit_server,
)

app = FastAPI(title="ChatKit API")

_chatkit_server: TraccarAssistantServer | None = create_chatkit_server()


def get_chatkit_server() -> TraccarAssistantServer:
    if _chatkit_server is None:
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail=(
                "ChatKit dependencies are missing. Install the ChatKit Python "
                "package to enable the conversational endpoint."
            ),
        )
    return _chatkit_server


@app.get("/chatkit/{filename}")
async def get_file(filename: str) -> Response:
    """Serve report files generated by the chat assistant."""
    file_path = REPORTS_DIR / filename

    # Security check: ensure the file is within the reports directory
    if not file_path.is_relative_to(REPORTS_DIR):
        raise HTTPException(status_code=400, detail="Invalid file path")

    if not file_path.exists():
        raise HTTPException(status_code=404, detail="Report file not found")

    # Determine media type based on file extension
    if filename.endswith(".html"):
        # Serve HTML directly in browser
        with open(file_path, "r", encoding="utf-8") as f:
            content = f.read()
        return Response(content=content, media_type="text/html")
    else:
        # Serve JSON files
        return FileResponse(path=file_path, media_type="application/json", filename=filename)


@app.post("/chatkit")
async def chatkit_endpoint(
    request: Request, server: TraccarAssistantServer = Depends(get_chatkit_server)
) -> Response:
    payload = await request.body()
    result = await server.process(payload, {"request": request})
    if isinstance(result, StreamingResult):
        return StreamingResponse(result, media_type="text/event-stream")
    if hasattr(result, "json"):
        return Response(content=result.json, media_type="application/json")
    return JSONResponse(result)


@app.get("/health")
async def health_check() -> dict[str, str]:
    return {"status": "healthy"}
