"""FastAPI entrypoint wiring the ChatKit server and REST endpoints."""

from __future__ import annotations

import logging
import time

import httpx
from chatkit.server import StreamingResult
from fastapi import Depends, FastAPI, HTTPException, Request, status
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import FileResponse, Response, StreamingResponse
from starlette.responses import JSONResponse

from .chat import (
    REPORTS_DIR,
    TraccarAssistantServer,
    create_chatkit_server,
    screenshot_tasks,
)
from .traccar import _get_cookie, _get_traccar_url

logger = logging.getLogger(__name__)

app = FastAPI(title="ChatKit API")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)

_chatkit_server: TraccarAssistantServer | None = create_chatkit_server()


def _real_ip(request: Request) -> str:
    """Get the real client IP behind Cloudflare (o2o worker setup)."""
    xff = request.headers.get("X-Forwarded-For", "")
    if xff:
        return xff.split(",")[0].strip()
    return request.headers.get("CF-Connecting-IP") or (
        request.client.host if request.client else "unknown"
    )


@app.middleware("http")
async def log_requests(request: Request, call_next):
    ip = _real_ip(request)
    logger.info(
        "%s %s %s %s", ip, request.method, request.url.path, request.headers.get("cf-ipcountry")
    )
    start = time.monotonic()
    try:
        response = await call_next(request)
    except Exception:
        logger.exception(
            "%s %s failed after %.2fs", request.method, request.url.path, time.monotonic() - start
        )
        raise
    # For streaming responses (e.g. /chatkit's SSE) this is time-to-first-byte,
    # not total duration -- the body streams after this returns. See the
    # per-stream timing logged in chatkit_endpoint for the true duration.
    elapsed = time.monotonic() - start
    logger.info(
        "%s %s -> %s in %.2fs", request.method, request.url.path, response.status_code, elapsed
    )
    if elapsed > 10:
        logger.warning(
            "Slow request: %s %s took %.2fs before response start",
            request.method,
            request.url.path,
            elapsed,
        )
    return response


def get_chatkit_server() -> TraccarAssistantServer:
    if _chatkit_server is None:
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail=(
                "ChatKit dependencies are missing. Install the ChatKit Python "
                "package to enable the conversational endpoint."
            ),
        )
    return _chatkit_server


@app.api_route("/api/{path:path}", methods=["GET", "POST", "PUT", "DELETE"])
async def proxy_traccar(request: Request, path: str) -> Response:
    """Reverse-proxy /api/* requests to the Traccar server."""
    traccar_url = f"{_get_traccar_url(request).rstrip('/')}/api/{path}"
    if request.url.query:
        traccar_url += f"?{request.url.query}"

    cookie = _get_cookie(request)
    headers = {"Accept": "application/json"}
    if cookie:
        headers["Cookie"] = cookie
    content_type = request.headers.get("content-type")
    if content_type:
        headers["Content-Type"] = content_type

    body = await request.body()

    start = time.monotonic()
    async with httpx.AsyncClient(timeout=25) as client:
        resp = await client.request(
            request.method,
            traccar_url,
            headers=headers,
            content=body or None,
        )
    elapsed = time.monotonic() - start
    logger.info("%s %s took %.2fs", request.method, traccar_url, elapsed)
    if elapsed > 5:
        logger.warning("Slow proxy_traccar: %s %s took %.2fs", request.method, traccar_url, elapsed)

    excluded = {"transfer-encoding", "content-encoding", "content-length"}
    resp_headers = {k: v for k, v in resp.headers.items() if k.lower() not in excluded}
    return Response(content=resp.content, status_code=resp.status_code, headers=resp_headers)


@app.get("/chatkit/{filename}")
async def get_file(filename: str) -> Response:
    """Serve report files generated by the chat assistant."""
    file_path = REPORTS_DIR / filename

    # Security check: ensure the file is within the reports directory
    if not file_path.is_relative_to(REPORTS_DIR):
        raise HTTPException(status_code=400, detail="Invalid file path")

    task = screenshot_tasks.get(filename)
    if task:
        wait_start = time.monotonic()
        await task
        logger.info(
            "get_file: %s waited %.2fs for pending screenshot task",
            filename,
            time.monotonic() - wait_start,
        )
    if not file_path.exists():
        raise HTTPException(status_code=404, detail="Report file not found")

    # Determine media type based on file extension
    if filename.endswith(".html"):
        # Serve HTML directly in browser
        with open(file_path, "r", encoding="utf-8") as f:
            content = f.read()
        return Response(content=content, media_type="text/html")
    elif filename.endswith(".png"):
        return FileResponse(path=file_path, media_type="image/png")
    else:
        # Serve JSON files
        return FileResponse(path=file_path, media_type="application/json", filename=filename)


async def _timed_sse_stream(result: StreamingResult, label: str):
    """Re-yield an SSE stream while logging its true end-to-end duration.

    The `log_requests` middleware only measures time-to-first-byte for a
    streaming response (it returns as soon as headers are ready, well before
    the body is fully sent). This is what actually accounts for the whole
    request lifetime that a Vercel proxy timeout would be measured against.

    Uses try/finally rather than try/except/else: when a client disconnects
    (which is exactly what a Vercel proxy timeout looks like from here), the
    server cancels this generator by throwing GeneratorExit/CancelledError
    into it -- neither is an Exception subclass, so `except Exception` does
    not catch it and a plain post-loop log line would never run. finally
    still runs, so the cancelled case is the one case we most need logged.
    """
    start = time.monotonic()
    chunk_count = 0
    byte_count = 0
    outcome = "cancelled"
    logger.info("%s stream starting", label)
    try:
        async for chunk in result:
            chunk_count += 1
            byte_count += len(chunk)
            yield chunk
        outcome = "done"
    except Exception:
        outcome = "error"
        raise
    finally:
        elapsed = time.monotonic() - start
        logger.info(
            "%s stream %s: %.2fs, %d chunks, %d bytes",
            label,
            outcome,
            elapsed,
            chunk_count,
            byte_count,
        )
        if outcome != "done" or elapsed > 20:
            logger.warning(
                "Slow/incomplete %s stream (%s): %.2fs, %d chunks",
                label,
                outcome,
                elapsed,
                chunk_count,
            )


@app.post("/chatkit")
async def chatkit_endpoint(
    request: Request, server: TraccarAssistantServer = Depends(get_chatkit_server)
) -> Response:
    payload = await request.body()
    process_start = time.monotonic()
    result = await server.process(payload, {"request": request})
    logger.info("server.process took %.2fs", time.monotonic() - process_start)
    if isinstance(result, StreamingResult):
        return StreamingResponse(
            _timed_sse_stream(result, "chatkit"), media_type="text/event-stream"
        )
    if hasattr(result, "json"):
        return Response(content=result.json, media_type="application/json")
    return JSONResponse(result)


@app.get("/health")
async def health_check() -> dict[str, str]:
    return {"status": "healthy"}
